BlogMvcErtan/Controllers/AdminUyeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlogMvcErtan.Models;
using PagedList;
using PagedList.Mvc;

namespace BlogMvcErtan.Controllers
{
    public class AdminUyeController : Controller
    {
        Db_Blog db = new Db_Blog();
        // GET: AdminUye
        public ActionResult UyeListele(int sayfa=1)
        {
            return View(db.Uyelers.OrderByDescending(x=>x.Tarih).ToPagedList(sayfa,10));
        }
        public ActionResult UyeDetay(int id) {
            var gelenVeri = db.Uyelers.Where(x => x.UyeId == id).FirstOrDefault();
            if (gelenVeri==null)
            {
                return HttpNotFound();
            }
            return View(gelenVeri);
        }

        public ActionResult UyeSil(int id)
        {
            var gelenVeri = db.Uyelers.Where(x => x.UyeId == id).FirstOrDefault();
            if (gelenVeri==null)
            {
                return HttpNotFound();
            }
            return View(gelenVeri);
        }
        [HttpPost,ActionName("UyeSil")]
        public ActionResult SilOk(int id) {
            var gelenVeri = db.Uyelers.Where(x => x.UyeId == id).FirstOrDefault();
            
           

            if (gelenVeri == null)
            {
                return HttpNotFound();
            }
            foreach (var item in db.Yorumlars.Where(x => x.UyeId == id).ToList())
            {
                db.Yorumlars.Remove(item);
            }
            

            
            db.SaveChanges();

            if (System.IO.File.Exists(Server.MapPath(gelenVeri.UyeFoto)))
            {
                System.IO.File.Delete(Server.MapPath(gelenVeri.UyeFoto));
            }
            db.Uyelers.Remove(gelenVeri);
            db.SaveChanges();
            return RedirectToAction("UyeListele");
        }
    }
}

BlogMvcErtan/Views/AdminUye/UyeDetay.cshtml
@model BlogMvcErtan.Models.Uyeler

@{
    ViewBag.Title = "UyeDetay";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>UyeDetay</h2>

<div>
    <h4>Uyeler</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Yetkilendirme.Yetkisi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Yetkilendirme.Yetkisi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KullanıcıAdı)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KullanıcıAdı)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UyeAdSoyad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UyeAdSoyad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UyeFoto)
        </dt>

        <dd>
           <img src="~/img/uyefoto/@Model.UyeId" class="img-circle" width="100"/>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tarih)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Listeye geri dön", "UyeListele","AdminUye",new { @class="btn btn-primary"})
</p>

BlogMvcErtan/Views/AdminUye/UyeListele.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<BlogMvcErtan.Models.Uyeler>

@{
    ViewBag.Title = "UyeListele";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}




<table class="table">
    <tr>
        <th>
            Yetki
        </th>
        <th>
            Kullanıcı Adı
        </th>
        <th>
            Şifre
        </th>
        <th>
            Ad Soyad
        </th>
        <th>
            Resim
        </th>
        <th>
            Tarih
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Yetkilendirme.Yetkisi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.KullanıcıAdı)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UyeAdSoyad)
        </td>
        <td>
            <img src="~/img/uyefoto/@item.UyeFoto" class="img-circle" width="100"/>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tarih)
        </td>
        <td>        
            @Html.ActionLink("Detay", "UyeDetay", new { id=item.UyeId }) |
            @Html.ActionLink("Sil", "UyeSil", new { id=item.UyeId })
        </td>
    </tr>
}

</table>
<div class="pagedList col-md-4 col-md-offset-4">

    @Html.PagedListPager(Model, sayfa => Url.Action("UyeListele", new { sayfa }), PagedListRenderOptions.PageNumbersOnly)
</div>

BlogMvcErtan/Views/AdminUye/UyeSil.cshtml
@model BlogMvcErtan.Models.Uyeler

@{
    ViewBag.Title = "UyeSil";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>UyeSil</h2>

<h3>Uyeyi silmek istiyor musunuz?</h3>
<div>
    <h4>Uyeler</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Yetkilendirme.Yetkisi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Yetkilendirme.Yetkisi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KullanıcıAdı)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KullanıcıAdı)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UyeAdSoyad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UyeAdSoyad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UyeFoto)
        </dt>

        <dd>
            <img src="~/img/uyefoto/@Model.UyeFoto"/>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tarih)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Listeye geri dön", "UyeleriListele","AdminUye",new { @class="btn btn-primary"})
        </div>
    }
</div>